use std::cell::Cell;
use std::fmt::Display;

use jni::objects::{JObject, JValue};
use jni::{Env, EnvUnowned, Outcome, jni_sig, jni_str};

pub use jni::errors::Error as JniError;
pub type Result<T = ()> = std::result::Result<T, JniError>;

/// Rust wrapper around the `CallbackInfo` passed to a Mixin `@Inject` handler.
/// The JNI wrapper generated by `#[inject_macro::inject]` wraps its third
/// argument (jobject) in this struct and forwards it to the user function.
pub struct CallbackInfo<'local> {
    inner: JObject<'local>,
}

impl<'local> CallbackInfo<'local> {
    /// # Safety
    /// `inner` is a local ref valid only within the scope of the JNI function
    /// call. Normally this is called only from inject-macro-generated code.
    pub unsafe fn from_jobject(inner: JObject<'local>) -> Self {
        CallbackInfo { inner }
    }

    /// Calls `CallbackInfo.cancel()`. If the corresponding `@Inject` is not
    /// `cancellable = true`, the Java side throws `IllegalStateException`,
    /// which propagates as `JniError::JavaException`.
    pub fn cancel(&self) -> Result<()> {
        with_env(|env| {
            env.call_method(&self.inner, jni_str!("cancel"), jni_sig!(() -> void), &[])?;
            Ok(())
        })
    }
}

thread_local! {
    static CURRENT_ENV: Cell<*mut jni::sys::JNIEnv> = const { Cell::new(std::ptr::null_mut()) };
}

/// RAII guard created only inside the JNI wrapper generated by
/// `#[inject_macro::inject]`. Until dropped, it stores the current JNIEnv
/// pointer in a thread-local so wrapper functions like `api::println` can
/// obtain the env without taking it as an argument.
pub struct EnvGuard {
    prev: *mut jni::sys::JNIEnv,
}

impl EnvGuard {
    /// # Safety
    /// `env` is valid only within the lifetime of the calling JNI function.
    /// The stored raw pointer must not be used after this guard is dropped.
    pub unsafe fn enter(env: &EnvUnowned) -> Self {
        let raw = env.as_raw();
        let prev = CURRENT_ENV.with(|c| c.replace(raw));
        EnvGuard { prev }
    }
}

impl Drop for EnvGuard {
    fn drop(&mut self) {
        CURRENT_ENV.with(|c| c.set(self.prev));
    }
}

fn with_env<T>(f: impl FnOnce(&mut Env) -> Result<T>) -> Result<T> {
    let raw = CURRENT_ENV.with(|c| c.get());
    assert!(
        !raw.is_null(),
        "api::* called outside of a #[inject] function"
    );
    // SAFETY: EnvGuard has registered the env of the JNI function currently
    // active on this thread, so the pointer is a valid attachment for the
    // duration of that call. Since 0.22 the JNI API lives on `Env`, reachable
    // only by upgrading an `EnvUnowned` via `with_env`.
    let mut unowned = unsafe { EnvUnowned::from_raw(raw) };
    match unowned.with_env(f).into_outcome() {
        Outcome::Ok(t) => Ok(t),
        Outcome::Err(e) => Err(e),
        // `with_env` catches panics; re-raise to preserve unwinding semantics.
        Outcome::Panic(payload) => std::panic::resume_unwind(payload),
    }
}

/// Calls `System.out.println(value.to_string())` over JNI.
pub fn println<T: Display>(value: T) -> Result<()> {
    let s = value.to_string();
    with_env(|env| -> Result<()> {
        let jstr = env.new_string(&s)?;
        let system_cls = env.find_class(jni_str!("java/lang/System"))?;
        let out =
            env.get_static_field(&system_cls, jni_str!("out"), jni_sig!(java.io.PrintStream))?;
        let out_obj = out.l()?;
        env.call_method(
            &out_obj,
            jni_str!("println"),
            jni_sig!((java.lang.String) -> void),
            &[JValue::from(&jstr)],
        )?;
        Ok(())
    })
}
